version: '3.8'

services:
  # Banco de Dados
  postgres:
    image: postgres:15-alpine
    container_name: price_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pricedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache
  redis:
    image: redis:alpine
    container_name: price_cache
    ports:
      - "6379:6379"

  # Interface gráfica para ver o banco (Opcional, mas útil)
  adminer:
    image: adminer
    ports:
      - "8081:8080"

volumes:
  postgres_data: